### ISSUE TITLE
Ordinal Non-negative Matrix Factorization for Recommendation

### ISSUE THREAD

**Issue by loretoparisi** [Oligou/dcPF#1]
Any plan to release the code for `Ordinal Non-negative Matrix Factorization for Recommendation`

Thank you!

**Comment by Oligou** [comment]
Hello @loretoparisi ,
The code for the article "Ordinal Non-negative Matrix Factorization for Recommendation" is now available: https://github.com/Oligou/OrdNMF.
arXiv: https://arxiv.org/abs/2006.01034

**Comment by loretoparisi** [comment]
Thank you very much!
